name: customer-segmentation-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.12
  - pip=21.2.4
  - numpy=1.21.6
  - pandas=1.3.5
  - scikit-learn=1.0.2
  - xgboost=1.5.1
  - matplotlib=3.5.1
  - seaborn=0.11.2
  - plotly=5.6.0
  - jupyter=1.0.0
  - ipykernel=6.9.1
  - notebook=6.4.8
  - scipy=1.7.3
  - statsmodels=0.13.2
  - missingno=0.5.1
  - python-dotenv=0.19.2
  - tqdm=4.62.3
  - joblib=1.1.0
  - pyyaml=6.0
  - requests=2.27.1
  - pip:
    - azureml-core==1.45.0
    - azureml-defaults==1.45.0
    - azureml-pipeline-core==1.45.0
    - azureml-pipeline-steps==1.45.0
    - azureml-telemetry==1.45.0
    - azureml-train-automl==1.45.0
    - azureml-widgets==1.45.0
    - azure-storage-blob==12.14.1
    - azure-identity==1.8.0
    - azure-keyvault-secrets==4.5.0
    - mlflow==1.26.1
    - hyperopt==0.2.7
    - optuna==3.0.5
    - shap==0.40.0
    - lime==0.2.0.1
    - eli5==0.13.0
    - imbalanced-learn==0.9.1
    - category-encoders==2.4.1
    - feature-engine==1.3.0
    - pandas-profiling==3.5.0
    - sweetviz==2.1.4
    - autoviz==0.1.36